<a href="https://colab.research.google.com/github/esnakaridharanioffical-lgtm/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.

**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

**Import NumPy in Python**

In [1]:
import numpy as np

**NumPy Array Creation**

In [2]:
# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [3]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


**Create a 2-D NumPy Array**

In [4]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


**Create a 3-D NumPy Array**

In [5]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [6]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)


int64


In [7]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array1.dtype)

int64


In [8]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(array1.dtype)

int64


**Check dimensions of an Numpy Array**

In [9]:
array1 = np.array([2, 4, 6])
print(array1.ndim)

1


In [11]:
array2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array2.ndim)

2


In [12]:
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(array3.ndim)

3


**Check Size of Numpy array**

In [13]:
print(array1.size)

3


In [14]:
print(array2.size)

8


In [15]:
print(array3.size)

24


**NumPy Array shape Attribute**




In [16]:
print(array1.shape)

(3,)


In [17]:
print(array2.shape)

(2, 4)


In [18]:
print(array3.shape)

(2, 3, 4)


**NumPy Array itemsize Attribute**

In [19]:
array1 = np.array([6, 7, 8, 10, 13])
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)

8
4


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [20]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7d30dc0e1840>
Data of array2 is:  <memory at 0x7d30c1deca00>


**Access Array Elements Using Index**

In [21]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


**Modify Array Elements Using Index**

In [22]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [51]:
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
array2[0,2]=7
print(array2)

[[1 2 7]
 [6 7 8]]


**2-D NumPy Array Indexing**

In [23]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


**NumPy Statistical Functions**

Functions

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

In [24]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)
print(median)

3.0


In [25]:
array2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
median=np.median(array2)
print(median)

4.5


In [26]:
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
median=np.median(array3)
print(median)

12.5


**Compute Mean Using NumPy**

In [27]:
mean_marks = np.mean(array1)

print(mean_marks)

3.0


In [28]:
mean_marks = np.mean(array2)

print(mean_marks)

4.5


In [29]:
mean_marks = np.mean(array3)

print(mean_marks)

12.5


**Standard Deviation of NumPy Array**

In [31]:
std_marks = np.std(array1)
print(std_marks)

1.4142135623730951


In [33]:
std_marks = np.std(array2)
print(std_marks)

2.29128784747792


In [34]:
std_marks = np.std(array3)
print(std_marks)

6.922186552431729


**Numpy Percentile**

In [36]:
std_marks = np.percentile(array1,75)
print(std_marks)

4.0


In [37]:
std_marks = np.percentile(array2,60)
print(std_marks)

5.2


In [38]:
std_marks = np.percentile(array3,90)
print(std_marks)

21.7


**Numpy min**

In [39]:
std_marks = np.min(array1)
print(std_marks)

1


In [40]:
std_marks = np.min(array2)
print(std_marks)

1


In [41]:
std_marks = np.min(array3)
print(std_marks)

1


**Numpy max**

In [42]:
std_marks = np.max(array1)
print(std_marks)

5


In [43]:
std_marks = np.max(array2)
print(std_marks)

8


In [44]:
std_marks = np.max(array3)
print(std_marks)

24


**Array Arithmetic Operations**

In [47]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
z = np.add(array1,array2)
print("Addition of x and y:\n", z)

z = np.subtract(array1,array2)
print("Subtraction of y from x:\n", z)

z = np.multiply(array1,array2)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 2  4  6  8]
 [ 6  8 10 12]]
Subtraction of y from x:
 [[ 0  0  0  0]
 [-4 -4 -4 -4]]
Element-wise multiplication of x and y:
 [[ 1  4  9 16]
 [ 5 12 21 32]]


**Append Arrays**

In [48]:
import numpy as np

my_array = np.array([1,2,3,4])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print("new_array:", new_array)

# Print `my_array` after appending
print("my_array after appending:", my_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]


**Appending to my_2d_array**

In [49]:
import numpy as np

my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_2d_array` before appending
print("my_2d_array before appending:\n", my_2d_array)

# Append an extra column to `my_2d_array`
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)

# Print `new_2d_array`
print("new_2d_array:\n", new_2d_array)

# Print `my_2d_array` after appending
print("my_2d_array after appending:\n", my_2d_array)

my_2d_array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
new_2d_array:
 [[1 2 3 4 7]
 [5 6 7 8 8]]
my_2d_array after appending:
 [[1 2 3 4]
 [5 6 7 8]]


**Insert and Delete Array Elements**

In [50]:
import numpy as np
my_array = np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Insert `5` at index 1
np.insert(my_array, 1, 5)

# Delete the value at index 1
np.delete(my_array,[1])

array([1, 3, 4])